ncl-icb-analytics/dbt-OLIDS

- models/intermediate/programme/valproate/int_valproate_araf_events.yml
- models/intermediate/programme/valproate/int_valproate_araf_referral_events.yml
- models/intermediate/programme/valproate/int_valproate_neurology_events.yml
- models/intermediate/programme/valproate/int_valproate_psychiatry_events.yml
- models/marts/programme/valproate/dim_valproate_action_status.yml
- models/marts/programme/valproate/dim_valproate_araf.yml
- models/marts/programme/valproate/dim_valproate_araf_referral.yml
- models/marts/programme/valproate/dim_valproate_db_scope.yml
- models/marts/programme/valproate/dim_valproate_neurology.yml
- models/marts/programme/valproate/dim_valproate_ppp_status.yml
- models/marts/programme/valproate/dim_valproate_psychiatry.yml
- Simplify lengthy business purpose sections in valproate YAML descriptions
- Focus on concise business logic explanations rather than verbose purpose statements
- Emphasise dashboard scope context for dim_valproate_db_scope table
- Condensed business purpose sections into technical business logic explanations
- Removed repetitive business purpose headers across all valproate dimension tables
- Updated intermediate table descriptions to focus on code category filtering logic
- All descriptions now reflect actual SQL implementation rather than abstract purposes
- All dim_valproate_* YAML files in marts/programme/valproate/
- All int_valproate_* YAML files in intermediate/programme/valproate/
> feat: simplify valproate YAML descriptions focusing on business logic

- models/intermediate/programme/valproate/int_valproate_araf_events.yml
- models/intermediate/programme/valproate/int_valproate_araf_referral_events.yml
- models/intermediate/programme/valproate/int_valproate_neurology_events.yml
- models/intermediate/programme/valproate/int_valproate_psychiatry_events.yml
- models/marts/programme/valproate/dim_valproate_action_status.yml
- models/marts/programme/valproate/dim_valproate_araf.yml
- models/marts/programme/valproate/dim_valproate_araf_referral.yml
- models/marts/programme/valproate/dim_valproate_db_scope.yml
- models/marts/programme/valproate/dim_valproate_neurology.yml
- models/marts/programme/valproate/dim_valproate_ppp_status.yml
- models/marts/programme/valproate/dim_valproate_psychiatry.yml
Follow-up fix to PR #71 to ensure proper bullet point formatting in valproate YAML descriptions.
- Add blank lines between bullet points in Business Logic sections
- Ensures proper rendering when displayed in DBT documentation
- Prevents bullet points from running together in a single line
- All dim_valproate_* YAML files in marts/programme/valproate/
- All int_valproate_* YAML files in intermediate/programme/valproate/
- Follow-up to PR #71 which simplified the business purpose descriptions
> fix: add proper line breaks between bullet points in valproate YAML descriptions

- models/intermediate/person_attributes/int_patient_registrations.sql
- models/marts/organisation/dim_person_current_practice.sql
- models/marts/organisation/dim_person_historical_practice.sql
- models/marts/organisation/dim_person_historical_practice.yml
• Fixed dim_person_current_practice to ensure exactly 1 row per person
• Removed CURRENT_DATE() calculations across all models to support incremental loading
• Improved column structure and ordering for better usability
- Removed CURRENT_DATE() from is_current_registration logic (now based on NULL end dates)
- Removed CURRENT_DATE() from registration_duration_days calculation
- Removed CURRENT_DATE() from effective_end_date logic
- Simplified registration_status to Active/Historical only
- Added person_id filtering to ensure only valid person records
- Removed CURRENT_DATE() from registration_type logic
- Simplified registration_type to Open/Closed only
- Removed redundant person_id filtering (handled upstream)
- Added ROW_NUMBER() deduplication to ensure exactly 1 row per person
- Added …
> fix: ensure dim_person_current_practice has exactly 1 row per person and supports incremental loading

- models/intermediate/organisation/int_organisation_borough_mapping.sql
• Add manual override for Medicus Select Care (practice code Y03103) to consistently map to Enfield borough
• Resolve awkward multiple borough mappings that were causing reporting issues
• Align with parent organisation location (Medicus Health Partners in Enfield)
Medicus Select Care practices were getting mapped to multiple boroughs through historic CCG relationships, creating inconsistent reporting. These practices provide cross-borough services to patients removed from other practices due to violence, but need a single borough assignment for clean reporting.
- Manual CASE statement override in `int_organisation_borough_mapping.sql` 
- Filter logic to prevent duplicate rows for practice Y03103
- Updated documentation explaining the special handling rationale
• Consistent single borough …
> fix: set Medicus Select Care practices to Enfield borough

- models/marts/programme/valproate/dim_valproate_action_status.sql
- models/marts/programme/valproate/dim_valproate_action_status.yml
- models/marts/programme/valproate/dim_valproate_araf.sql
- models/marts/programme/valproate/dim_valproate_araf.yml
- Add action_order field (1-9 priority ranking) to dim_valproate_action_status with comprehensive business logic matching legacy model
- Add ARAF form type flags to dim_valproate_araf for distinguishing old/new annual risk acknowledgement forms
- Update YAML descriptions to reflect new fields and accurate business logic
- Fix field name reference from is_on_ld_register to is_on_register
- Added action_order field with 1-9 priority ranking system
- Added comprehensive business logic for pregnancy, PPP, ARAF status assessment
- Added learning disability and permanent absence pregnancy risk flags
- Added risk classification and additional findings groupings
- Updated YAML metadata to reflect new fields
- Added has_old_annual_risk_acknowledgement_form flag (concept code 1366401000000107)
- …
> fix: add missing key fields to valproate models

- macros/join_concept_display.sql
- models/marts/person_demographics/dim_person_sex.sql
- Created `join_concept_display` macro for dynamic concept lookups
- Updated `dim_person_sex` model to use the new macro instead of hardcoded concept IDs
- Tested successfully - Male/Female values are properly populated
1. **New macro**: `macros/join_concept_display.sql`
- Provides reusable pattern for joining concept tables
- Accepts source column and optional alias prefix parameters
- Returns proper table aliases for source_concept, concept_map, and target_concept
2. **Updated model**: `models/marts/person_demographics/dim_person_sex.sql`
- Replaced hardcoded gender concept IDs with dynamic lookup
- Uses `COALESCE(target_concept.display, source_concept.display, 'Unknown')`
- Maintains same functionality with more maintainable approach
Model has been tested and runs successfully with all …
> feat: add concept joining macro and update dim_person_sex

- .pre-commit-config.yaml
• Added SQLFluff to precommit hooks for automatic SQL formatting
• Configured to run silently without blocking commits
• Only formats staged SQL files in active development directories
• Provides lightweight, behind-the-scenes formatting improvements
• Added SQLFluff configuration to `.pre-commit-config.yaml`
• Restricted formatting to `models/`, `macros/`, `tests/`, and `analyses/` directories
• Used local hook with bash script to ensure it never blocks commits
• Disabled progress bar for cleaner output
• Automatic SQL formatting on commit
• No manual formatting required
• Consistent code style across the codebase
• Fast execution - only processes staged files
• Never blocks commits even if formatting fails
> feat: add SQLFluff auto-formatting to precommit hooks

- models/intermediate/person_attributes/int_ethnicity_all.sql
- models/marts/person_demographics/dim_person_birth_death.sql
- models/marts/person_demographics/dim_person_demographics.sql
- models/marts/person_demographics/dim_person_ethnicity.sql
- models/marts/person_demographics/dim_person_main_language.sql
- models/marts/person_demographics/dim_person_sex.sql
- models/marts/person_status/dim_person_active_patients.sql
- models/marts/person_status/dim_person_inactive_patients.sql
Fixed grain issues caused by many:many patient_person relationships across all dim_person tables. All tables now maintain proper person-level grain (one row per person_id).
Several dim_person tables were using `stg_olids_patient_person` as a base, which created many-to-many relationships resulting in duplicate person records when:
- Multiple patients linked to one person (historical records)
- Multiple persons linked to one patient (data quality issues)
Implemented three strategies based on data location:
- **int_ethnicity_all.sql**: Use `o.person_id` directly from observations, removed patient_person joins
- **dim_person_ethnicity.sql**: Use `dim_person` as base for complete coverage  
- **dim_person_main_language.sql**: Use `dim_person` as base for complete coverage
- …
> fix: resolve person-level grain issues across all dim_person tables

- models/staging/stg_olids_person.sql
Updates the `stg_olids_person` staging model to use the correct source table after the PERSON table was deleted from the source system.
- The original PERSON table was deleted from the source system
- `stg_olids_person` was referencing the non-existent PERSON table
- This caused compilation errors in models that depend on person data
- PERSON_BACKUP contains the same schema and data as the original PERSON table
- **Source table**: Changed from `PERSON` to `PERSON_BACKUP`
- **Column references**: Kept all existing column mappings (they exist in PERSON_BACKUP)
- **Comments**: Updated to clarify use of backup table
- ✅ Resolves compilation errors in downstream models
- ✅ Maintains compatibility with existing person-based dimensions
- ✅ No breaking changes to column structure or data types
- …
> fix: update stg_olids_person to use PERSON_BACKUP source table

- models/intermediate/medications/int_arb_medications_all.sql
- Fixed incorrect BNF code from '02050502' to '0205052' for ARB medications
- Simplified model to essential medication order data only
The `int_arb_medications_all` model was returning 0 results because it was using an incorrect BNF code '02050502' instead of the correct '0205052' for Angiotensin Receptor Blockers (ARBs).
Updated `get_medication_orders` call to use correct BNF code '0205052' and simplified model to focus on core medication data without complex categorisation.
> fix: correct BNF code for ARB medications

- profiles.yml.template
• Removed unused QA target configuration from profiles.yml template
• Updated comment to reflect only dev and prod environments
- Removed the entire `qa:` target section from the template
- Updated the default target comment to mention `--target prod` instead of referencing wrapper scripts
The QA target is no longer used in the project workflow, so removing it simplifies the configuration and prevents confusion.
> Remove QA target from profiles.yml template

- models/staging/stg_olids_person.sql
• Fixed stg_olids_person model that was failing due to referencing non-existent columns
• Model now runs successfully without errors
The model was trying to select two columns that don't exist in the PERSON_BACKUP source table:
- - 
1. **Commented out missing columns** with TODOs indicating possible alternatives
2. **Added available columns** that might be suitable replacements:
- \ (possible alternative to lds_business_key)
- \ (possible alternative to primary_patient_id)
3. **Added additional columns** for reference: \, \, 
- Model now runs without compilation errors
- No downstream models are affected (model is not referenced anywhere)
- TODOs added for future clarification on correct column mappings
Successfully ran: \dbt-fusion 2.0.0-beta.24
Loading profiles.yml
Finished 'run'  with …
> Fix stg_olids_person model missing columns error

- macros/get_medication_orders.sql
- macros/get_observations.sql
- models/intermediate/person_attributes/int_patient_person_unique.sql
• Refactored both macros to use native terminology joins instead of pre-aggregated mapped_concepts table
• Created int_patient_person_unique model to handle duplicate patient-person mappings
• Removed QUALIFY clause that was over-deduplicating and excluding valid persons
• Fixed issue where get_observations returned only 48 patients instead of expected 73
- **get_observations macro**: Replace `stg_codesets_mapped_concepts` with native joins through `CONCEPT_MAP → CONCEPT → COMBINED_CODESETS`
- **get_medication_orders macro**: Same native join pattern + improved cluster handling
- **int_patient_person_unique model**: New intermediate model that deduplicates patient-person mappings and filters null patient_id records
- **Performance**: Removed QUALIFY clause to prevent over-deduplication …
> fix: refactor get_observations and get_medication_orders macros to use native terminology joins

- macros/get_medication_orders.sql
- macros/get_observations.sql
- macros/get_observations_v2.sql
- models/intermediate/diagnoses/int_nafld_diagnoses_all.sql
- models/intermediate/medications/int_valproate_medications_all.sql
- models/intermediate/person_attributes/int_ethnicity_all.sql
- models/intermediate/person_attributes/int_ethnicity_qof.sql
- models/intermediate/person_attributes/int_patient_person_unique.sql
- models/intermediate/person_attributes/int_patient_registrations.sql
- models/intermediate/person_attributes/int_pregnancy_absence_risk_all.sql
- models/intermediate/programme/valproate/int_ppp_status_all.sql
- models/intermediate/programme/valproate/int_valproate_araf_events.sql
- models/intermediate/programme/valproate/int_valproate_araf_referral_events.sql
- models/intermediate/programme/valproate/int_valproate_neurology_events.sql
- models/intermediate/programme/valproate/int_valproate_psychiatry_events.sql
- models/marts/person_demographics/dim_person.sql
• Updated all models to use the new int_patient_person_unique model instead of raw stg_olids_patient_person
• Removed redundant deduplication logic where the new model is used
• Ensures consistent patient-person mapping across the entire codebase
• Depends on PR #124 which introduces the int_patient_person_unique model
**Dimension Models:**
- dim_person: Use int_patient_person_unique for patient aggregation
**Intermediate Models Updated:**
- int_patient_registrations: Use int_patient_person_unique, removed redundant ROW_NUMBER deduplication
- int_ethnicity_all: Use int_patient_person_unique, removed redundant QUALIFY deduplication
- All valproate programme models: int_valproate_araf_events, int_valproate_psychiatry_events, int_valproate_neurology_events, …
> feat: update models to use int_patient_person_unique for consistent patient-person mappings

- macros/get_medication_orders.sql
- macros/get_observations.sql
- models/intermediate/medications/int_asthma_medications_12m.sql
- models/intermediate/medications/int_asthma_medications_12m.yml
• Fixed asthma medication cluster ID from `ASTRX_COD` to `ASTTRT_COD` per QOF specification
• Added case-insensitive cluster ID matching to both `get_observations` and `get_medication_orders` macros
• Resolves issue where asthma register had lower than expected counts
1. **Wrong cluster ID**: Using `ASTRX_COD` instead of `ASTTRT_COD` as specified in QOF documentation
2. **Case sensitivity**: Cluster ID comparisons were case-sensitive, causing mismatches when data had different casing
According to QOF AST005 documentation:
- Field: `ASTTRT_DAT` using cluster `ASTTRT_COD`
- Description: "Date of the most recent asthma-related drug treatment code occurring within the 12-month period"
**Asthma Medication Model**:
- Changed `get_medication_orders(cluster_id='ASTRX_COD')` to …
> fix: correct asthma medication cluster and add case-insensitive cluster matching

- models/sources.yml
- models/staging/stg_olids_person.sql
• Updated `stg_olids_person` staging model to handle missing columns in the PERSON table
• Added alternative columns that exist in the current table structure
• Updated `sources.yml` to reflect actual table schema
**Commented out missing columns**:
- `lds_business_key` - Added TODO note suggesting `unique_reference` or `id` as alternatives
- `primary_patient_id` - Added TODO note suggesting `requesting_patient_id` or `id` as alternatives
**Added available columns**:
- `lds_datetime_data_acquired` - For data freshness tracking
- `unique_reference` - Alternative identifier
- `requesting_patient_id` - Alternative patient reference
The PERSON table schema appears to have changed, with some columns no longer available. This fix ensures the staging model can run successfully while documenting …
> fix: update stg_olids_person to handle missing columns in PERSON table

- models/marts/published_reporting_direct_care/population_health_needs_base.sql
Update comments to specify that all three source tables are designed with identical grain, ensuring clarity in the dataset's structure and maintaining a defensive approach with LEFT JOINs for comprehensive population coverage.
> docs: clarify business logic in population_health_needs_base

- models/intermediate/observations/int_bmi_all.sql
- models/intermediate/observations/int_bmi_latest.sql
Improves model architecture and performance:
- Move BMI risk sort key from int_bmi_latest to int_bmi_all for consistency
- Replace get_latest_events macro with simple QUALIFY clause in int_bmi_latest
- Add bmi_source field to latest model for transparency
- Simplifies SQL and improves readability
> refactor: simplify BMI models and move risk sort key to base model

- models/intermediate/observations/int_bmi_all.sql
- models/intermediate/observations/int_bmi_latest.sql
- models/intermediate/observations/int_bmi_qof.sql
- models/marts/data_quality/dq_bmi_issues.sql
Improves field naming consistency across BMI models:
- int_bmi_all: Updated both recorded and calculated BMI sections
- int_bmi_latest: Updated field reference
- int_bmi_qof: Updated assignment and selection
- dq_bmi_issues: Updated field reference
The simplified name 'result_value' is more intuitive than 'original_result_value'. All downstream models tested successfully.
> refactor: rename original_result_value to result_value in BMI models

- models/olids/intermediate/observations/int_bmi_all.sql
- models/olids/intermediate/observations/int_bmi_all.yml
- models/olids/intermediate/observations/int_bmi_latest.sql
- models/olids/intermediate/observations/int_bmi_latest.yml
- models/olids/intermediate/observations/int_bmi_qof.sql
- models/olids/intermediate/person_attributes/int_ethnicity_cardiometabolic_risk.sql
- models/olids/intermediate/person_attributes/int_ethnicity_cardiometabolic_risk.yml
- models/olids/marts/published_reporting_direct_care/population_health_needs_base.yml
Implements ethnicity-adjusted BMI categories per NICE guidance for populations with increased cardiometabolic risk at lower BMI levels.
- **`int_ethnicity_cardiometabolic_risk`**: Shared ethnicity model identifying populations requiring lower BMI thresholds (South Asian, Chinese, other Asian, Middle Eastern, Black African, African-Caribbean)
- **`int_bmi_all`**: 
- Added ethnicity-adjusted BMI categories (23-27.4 overweight, 27.5+ obese for risk populations)
- Fixed BMI over-calculation by excluding dates with existing recorded BMI
- Joined with new ethnicity model for risk assessment
- **`int_bmi_qof`**: 
- Integrated shared ethnicity model
- Added BAME classification for QOF requirements
- Included ethnicity-adjusted threshold flags
- **`int_bmi_latest`**: 
- Updated to support new …
> feat: implement ethnicity-adjusted BMI categories per NICE guidance

- macros/clean_practice_name.sql
- models/olids/intermediate/person_attributes/int_patient_registrations.sql
- models/olids/marts/organisation/dim_practice.sql
- models/olids/marts/person_demographics/dim_person_demographics.sql
- models/olids/marts/person_demographics/dim_person_demographics_historical.sql
• Standardise practice names with medical acronym capitalisation
• Reorder demographics columns - status flags after identifiers  
• Fix inactive_reason to prioritise death over registration status
• Add clean_practice_name macro - removes trailing dots, capitalises GP/NHS/PMS etc
• Move is_active, is_deceased, is_dummy_patient after person_id in both demographics models
• Deceased patients show 'Deceased' not 'Registration ended' in inactive_reason
> feat: standardise practice names and reorder demographics columns

- models/olids/marts/programme/flu/fct_flu_uptake.sql
- models/olids/marts/programme/flu/fct_flu_uptake_by_practice.sql
- models/olids/marts/programme/flu/fct_flu_uptake_by_practice.yml
- models/olids/marts/programme/flu/fct_flu_uptake_weekly.sql
- models/olids/marts/programme/flu/fct_flu_uptake_weekly.yml
- models/olids/marts/programme/flu/fct_flu_weekly_org.sql
- models/olids/marts/programme/flu/fct_flu_weekly_person.sql
- Simplified cervical screening models to focus on core programme tracking
- Added new weekly flu uptake model for time series analysis
- Enhanced existing flu vaccination models with clearer documentation
- Filtered fact table to only include eligible age range (25-64)
- Removed complex classification logic to focus on core tracking
- Added `fct_flu_uptake_weekly` model for weekly time series analysis
- Simplified aggregation logic in `fct_flu_uptake_by_practice`
- Updated YAML documentation for clarity and consistency
- Removed redundant date filtering from weekly models
> feat: simplify cervical screening and enhance flu vaccination models

- dbt_project.yml
- Remove hardcoded fallback value 'DATA_LAB_OLIDS_UAT' from SNOWFLAKE_TARGET_DATABASE environment variable configuration
- Ensures explicit environment configuration is required, preventing accidental use of default values
- Updated `dbt_project.yml` to use `env_var('SNOWFLAKE_TARGET_DATABASE')` without fallback value in three locations:
- Main model configuration
- OLIDS model configuration  
- Shared model configuration
This change ensures that the database target must be explicitly set via environment variable, preventing unintended deployments to the UAT database when the environment variable is not configured.
> fix: remove database fallback value in dbt_project.yml

- dbt_project.yml
- macros/get_medication_orders.sql
- macros/get_observations.sql
- models/olids/intermediate/performance/int_medication_orders_mapped.sql
- models/olids/intermediate/performance/int_observations_mapped.sql
- models/olids/intermediate/performance/int_performance.yml
- models/olids/intermediate/person_attributes/int_patient_person_unique.sql
- models/olids/marts/person_demographics/dim_person_main_language.sql
- models/olids/marts/person_status/dim_person_care_home.sql
- models/olids/marts/person_status/dim_person_is_carer.sql
- models/olids/marts/published_reporting_direct_care/population_health_needs_demographics_ltcs.yml
Major performance optimization that creates pre-mapped tables to eliminate expensive runtime joins in observation and medication queries.
- Creates `int_observations_mapped` and `int_medication_orders_mapped` incremental models
- Pre-joins concept mappings to avoid scanning 200GB+ at query time  
- Updates macros to use optimized tables with flexible cluster definitions
- Enhances patient-person bridge table with `sk_patient_id`
- Fixes downstream models to use proper relationships
- **Query scans reduced from 100GB+ to <1GB** for typical cluster-based queries
- **100-1000x performance improvement** expected for macro usage
- Enables efficient partition pruning via clustering
- Maintains flexible cluster definitions without rebuilding large tables
> feat: optimize observation and medication macros with pre-mapped performance tables

- .pre-commit-config.yaml
- models/olids/intermediate/performance/int_medication_orders_mapped.sql
- models/olids/intermediate/performance/int_observations_mapped.sql
- models/olids/intermediate/person_attributes/int_patient_person_unique.sql
- Change LEFT JOINs to INNER JOINs for concept mapping in performance models
- Remove unused person_id fields (rarely populated in source data)  
- Update int_patient_person_unique to use DISTINCT for deduplication
- Add perf to conventional commit types configuration
> perf: optimise concept mapping joins in performance models

- models/olids/intermediate/person_attributes/int_patient_person_unique.sql
- models/olids/marts/published_reporting_direct_care/population_health_needs_base_readable.sql
- models/olids/marts/published_reporting_direct_care/population_health_needs_demographics_ltcs.sql
- models/olids/marts/published_reporting_direct_care/population_health_needs_demographics_ltcs.yml
- models/olids/staging/stg_olids_patient_person.sql
- models/olids/staging/stg_olids_person.sql
Implements interim solution for person_id duplicate issues by generating deterministic hash-based person IDs from reliable sk_patient_id values at the staging layer.
- Source person_id contains duplicates causing data quality issues in registration models
- Registration analysis shows inflated counts due to duplicate person records  
- 250+ downstream models depend on reliable person_id for linking
**Staging Layer Changes:**
- **stg_olids_patient_person.sql**: Generate `person_id` as `'person-' || MD5(sk_patient_id)`
- **stg_olids_person.sql**: Generate matching `id` field using same hash logic
- Both models now materialized as tables with DISTINCT for consistency
- Preserve `original_person_id` fields for rollback capability
**Intermediate Layer:**
- **int_patient_person_unique.sql**: …
> feat: implement UUID-based person_id generation to fix duplicates

- models/olids/marts/programme/valproate/dim_valproate_action_status.sql
- models/olids/marts/programme/valproate/dim_valproate_action_status.yml
- models/olids/marts/programme/valproate/dim_valproate_araf.sql
- models/olids/marts/programme/valproate/dim_valproate_araf.yml
Fixed logical inconsistencies in valproate ARAF (Annual Risk Acknowledgement Form) date handling and action prioritisation that were causing incorrect clinical decision outputs.
**Issue:** Both `old_annual_risk_acknowledgement_form_info` and `new_annual_risk_acknowledgement_form_info` were showing the same generic `latest_specific_araf_form_date` instead of the actual date of each specific form type.
**Impact:** Patients with both old and new ARAF forms would show identical dates for both form types, making it impossible to distinguish which form was completed when.
**Fix:** 
- Added separate date calculations for old ARAF (SNOMED: `1366401000000107`) and new ARAF (SNOMED: `2078951000000106`)
- Info strings now show actual completion dates for each specific form type
- Added …
> fix: correct valproate ARAF date logic and action prioritisation

- dbt_project.yml
- models/olids/marts/organisation/dim_practice_neighbourhood.yml
- models/shared/staging/schema.yml
- Fix dim_practice_neighbourhood.yml to reference correct model name
- Fix shared staging schema.yml to use correct staging model name  
- Add on-run-start hook to display connection details (role, warehouse, database, schema)
Resolves test failures caused by incorrect model references in YAML files:
- `dim_neighbourhood_registered` → `dim_practice_neighbourhood` 
- `stg_reference_neighbourhood_registered_lookup` → `stg_reference_practice_neighbourhood_lookup`
Also adds connection info display when running dbt commands to show current role, warehouse, database, and schema.
> fix: correct model references and add connection info display
